# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a288ae480fb754356283ffdbd51db7a2f8821997d09015495fa73fe61fed0c55a5d791790aa5fb2b427ff057cf6ca1d423b372e4dcb45a6838e3201727ff849

test:
  secret_key_base: 4efbcd1e82efdaf70be9d38de1b591699681f03deff0c8259450b39a57d42a13f7ac8675dbb8c17318508b4d7e93c5a008204cc456ce071ab538a44e4bc54903

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
